name: Build and Release Executables

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: Voill_Linux
            asset_name: Voill_Linux
          - os: windows-latest
            artifact_name: Voill_Windows.exe
            asset_name: Voill_Windows.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System C-Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev python3-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.10

      - name: Install Project Dependencies
        working-directory: ./backend
        run: |
          uv sync
          uv pip install pyinstaller

      - name: Build Executable with PyInstaller
        working-directory: ./backend
        run: |
          uv run pyinstaller --onefile --name="${{ matrix.artifact_name }}" main.py

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v2
        with:
          files: backend/dist/${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}